name: Compile GooseDroid

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch: # Te permite activar la compilación manualmente desde GitHub

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          # Al definir esto explícitamente, evitamos que GitHub intente buscar el paquete obsoleto 'tools'
          packages: 'platform-tools;build-tools;34.0.0;platforms;android-34'

      - name: Grant Execute Permission for Gradle
        run: chmod +x gradlew

      - name: Build APK (Debug)
        run: ./gradlew assembleDebug

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: GooseDroid-Debug-APK
          path: app/build/outputs/apk/debug/*.apk


